sonar.projectKey=DEFRA_gep-land-model-viewer-frontend
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/gep-land-model-viewer-frontend
sonar.links.ci=https://github.com/DEFRA/gep-land-model-viewer-frontend/actions
sonar.links.scm=https://github.com/DEFRA/gep-land-model-viewer-frontend
sonar.links.issue=https://github.com/DEFRA/gep-land-model-viewer-frontend/issues

sonar.sources=src/
sonar.exclusions=src/**/*.test.js
sonar.tests=src/
sonar.test.inclusions=src/**/*.test.js

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.cpd.exclusions=src/**/*.test.js,src/client/javascripts/map/config/map-styles.js
sonar.issue.ignore.multicriteria=testFunctionLength,testDuplicateLiterals,datasetClassBreaks
sonar.issue.ignore.multicriteria.testFunctionLength.ruleKey=javascript:S138
sonar.issue.ignore.multicriteria.testFunctionLength.resourceKey=**/*.test.js
sonar.issue.ignore.multicriteria.testDuplicateLiterals.ruleKey=javascript:S1192
sonar.issue.ignore.multicriteria.testDuplicateLiterals.resourceKey=**/*.test.js
sonar.issue.ignore.multicriteria.datasetClassBreaks.ruleKey=javascript:S109
sonar.issue.ignore.multicriteria.datasetClassBreaks.resourceKey=**/map/config/operational-datasets.js
